### ISSUE TITLE
Manager does not delete images not defined in the image YAML files

### ISSUE THREAD

**Issue by linwalth** [osism/openstack-image-manager#488]
Running the Image-Manager I found that the it does not delete images not defined in the image YAML files as intended. Using the --hide setting, It does not only keep the last 3, but /all/ old images, way beyond the versions defined in our respective YAML files.

Expected Behavior: The Image Manager keeps the last 3 Images (Hidden) and deletes, deactivates, all other images tagged managed_by_x.

**Comment by linwalth** [comment]
It would probably be good to have this functionality as a "Garbage Collection" flag with the manager command as there are some setups where deletion of an Image is impossible once there have been instances created from it. (COW)

**Comment by berendt** [comment]
Having a GC makes sense to me.

**Comment by sihensel** [comment]
Should be fixed with #506.
When using `multi=true`, only the newest image is kept, while all older ones are hidden/deactivated/deleted.

**Comment by linwalth** [comment]
> Should be fixed with #506. When using `multi=true`, only the newest image is kept, while all older ones are hidden/deactivated/deleted.

that is what the manager does, but the expected behavior is still not enacted:

https://github.com/osism/openstack-image-manager/issues/568

**Comment by berendt** [comment]
There is now a warning message for images not longer defined. But they will not be deleted by default.
